# MUTLI-STAGE DOCKERFILE for building a Python image
# STAGE 1: base_stage is the base image for both the development and dev-staging/staging/production images
# STAGE 2: development_only_stage is the image used for development (optimised for VSCode)

########################
# STAGE 1: base_stage #
########################

# STEP 1: Base image
# If you change the base image, you will need to update the
# PRE_FETCH_BASE_IMAGE variable in the .gitlab-ci.yml file also.
FROM python:3.12-slim-bullseye AS base_stage

# STEP 2: Variables
# ARG and ENV variables
#
USER root
ENV \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VIRTUALENVS_IN_PROJECT=false

ARG \
    OPT_DIRECTORY="/opt" \
    PYTHONUNBUFFERED=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_NO_CACHE_DIR=1 \
    PIP_VERSION=23.2.1 \
    POETRY_VERSION=2.2.0 \
    USER_NAME="appuser" \
    USER_DIRECTORY="/home/appuser"

ARG \
    USER_BASHRC="${USER_DIRECTORY:?}/.bashrc" \
    VENV_DIRECTORY="${OPT_DIRECTORY:?}/venv" \
    POETRY_HOME="${OPT_DIRECTORY:?}/poetry" \
    PIPX_HOME="${OPT_DIRECTORY:?}/pipx" \
    PIPX_BIN_DIR="${OPT_DIRECTORY:?}/pipx/bin" \
    POETRY_CACHE_DIR="${OPT_DIRECTORY:?}/poetry-cache" \
    PROJECT_DIRECTORY="${OPT_DIRECTORY:?}/repo"

ENV \
    PATH=${POETRY_HOME}/bin:${PIPX_BIN_DIR}:${PATH}

# STEP 3: Create a non-root user and directories
# Create a non-root user to avoid running as root
# Create directories for the project, poetry cache, pipx home and virtual environment
RUN \
    useradd "${USER_NAME:?}" --shell /bin/bash --create-home --home-dir "${USER_DIRECTORY:?}" \
    && mkdir -p "${PROJECT_DIRECTORY:?}" "${OPT_DIRECTORY:?}" "${POETRY_CACHE_DIR:?}" "${PIPX_HOME:?}" "${POETRY_HOME:?}" "${VENV_DIRECTORY:?}" "${PIPX_BIN_DIR:?}" \
    && chown -R "${USER_NAME:?}:${USER_NAME:?}" "${PROJECT_DIRECTORY:?}" "${USER_DIRECTORY:?}" "${OPT_DIRECTORY:?}" \
    && chmod -R 755 "${PROJECT_DIRECTORY:?}" "${USER_DIRECTORY:?}" "${OPT_DIRECTORY:?}"

# STEP 4: Install dependencies
# Install system dependencies
# - build-essential - to build Python packages that require compilation
# - nano/vim - text editors (useful to edit files in the container)
# - curl/wget - to fetch files from the internet
# - git - to support pre-commit hooks
# - iputils-ping/telnet - to test network connectivity


RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN \
    python3 -m pip install --upgrade pip==${PIP_VERSION:?} && \
    apt-get update --quiet && \
    apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    nano \
    curl \
    wget \
    vim \
    git \
    tree \
    iputils-ping \
    telnet \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install pipx \
    && pipx ensurepath \
    && pipx install poetry==$POETRY_VERSION

# STEP 5: Install python packages
# An venv in a Docker container allows isolation of dependencies
# and prevents conflicts with the system Python packages
#
# - The venv is created in /opt/venv and activated for the non-root user
# - The PATH is updated to include the venv bin directory
# - The VIRTUAL_ENV variable is set so that Python and pip will know
#   that they are in a virtual environment
USER $USER_NAME
WORKDIR $OPT_DIRECTORY
RUN \
    python3 -m venv ${VENV_DIRECTORY} &&  \
    echo "source ${VENV_DIRECTORY}/bin/activate" >> "${USER_BASHRC}"
ENV \
    PATH="${VENV_DIRECTORY}/bin:${PATH}" \
    VIRTUAL_ENV=${VENV_DIRECTORY}
# Copy dependency control files and install dependencies
# 1. only the dependency control files for Poetry (equivalent to "requirements.txt"
#    if you have never seen Poetry *.lock and *.toml files before)
#    The unsual square brakets in `poetry.loc[k]` provides GLOB/REGEX syntax which ensures
#    IDEMPOTENCY for the build (i.e. Docker builds correctly the first and every subsequent time).
#    Initially, `poetry.lock` may be absent as it is only created after the first `poetry install`
#    This syntax lets COPY conditionally include it without the build failing if missing.
# 2. .gitignore as it is used by precommit-check in a post build stage of the CICD
WORKDIR $PROJECT_DIRECTORY
COPY --chown="${USER_NAME}:${USER_NAME}" [".gitignore", "pyproject.toml", "poetry.loc[k]", "./"]
RUN \
    poetry install --no-root --no-directory --no-cache \
    && chown -R "${USER_NAME}:${USER_NAME}" ${VENV_DIRECTORY}

# STEP 6: Copy project files and install the project
# Copy the src, test and other code of the project into the container.
# Then install the project itself via Poetry
COPY --chown="${USER_NAME}:${USER_NAME}" . "${PROJECT_DIRECTORY}"
RUN \
    poetry install --no-cache \
    && chown -R "${USER_NAME}:${USER_NAME}" "${USER_DIRECTORY}" "${PROJECT_DIRECTORY}"

# Use user "appuser" to run the build commands below and the server itself.
USER "${USER_NAME}"

###################################
# STAGE 2: development_only_stage #
# - This stage is optional        #
# - It is optimised for VSCode    #
###################################

# To develop from the container we need add some extra directories to work nicely with VSCode
FROM base_stage AS development_only_stage
USER root

# Install hubflow to allow for git flow style development
WORKDIR "${USER_DIRECTORY}"
RUN git config --global --add safe.directory "${USER_DIRECTORY}/gitflow" \
    && git config --global --add safe.directory "${USER_DIRECTORY}/gitflow/shFlags" \
    && git clone https://github.com/datasift/gitflow \
    && chown -R "${USER_NAME}:${USER_NAME}" gitflow \
    && cd gitflow \
    && ./install.sh

# Return back to the project directory for the entrypoint
WORKDIR "${PROJECT_DIRECTORY}"
USER "${USER_NAME}"

# Prepare the directory for the VSCode server extensions and bash history
RUN mkdir -p "${USER_DIRECTORY}/.vscode-server/extensions" \
    "${USER_DIRECTORY}/.vscode-server-insiders/extensions" \
    && chown -R "${USER_NAME}:${USER_NAME}" \
    "${USER_DIRECTORY}/.vscode-server" \
    "${USER_DIRECTORY}/.vscode-server-insiders" && \
    SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=${USER_DIRECTORY}/.commandhistory/.bash_history" \
    && mkdir "${USER_DIRECTORY}/.commandhistory/" \
    && touch "${USER_DIRECTORY}/.commandhistory/.bash_history" \
    && chown -R "${USER_NAME}:${USER_NAME}" "${USER_DIRECTORY}/.commandhistory/" \
    && echo "$SNIPPET" >> "/home/$USER_NAME/.bashrc"

# Setup the pre-commit hooks so that they are run before each commit
RUN pre-commit install --install-hooks
