# MUTLI-STAGE DOCKERFILE for building a Python image
# STAGE 1: base_stage is the base image for both the development and dev-staging/staging/production images
# STAGE 2: development_only_stage is the image used for development (optimised for VSCode)

########################
# STAGE 1: base_stage #
########################

# STEP 1: Base image
# If you change the base image, you will need to update the
# PRE_FETCH_BASE_IMAGE variable in the .gitlab-ci.yml file also.
FROM python:3.12-slim-bullseye AS base_stage

# STEP 2: Variables
# ARG and ENV variables
# 
USER root
ENV \
    LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VIRTUALENVS_IN_PROJECT=false

ARG \
    OPT_DIRECTORY="/opt" \
    PYTHONUNBUFFERED=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_NO_CACHE_DIR=1 \
    PIP_VERSION=23.2.1 \
    POETRY_VERSION=2.2.0 \
    USER_NAME="admin" \
    USER_DIRECTORY="/home/admin"

ARG \
    USER_BASHRC="${USER_DIRECTORY:?}/.bashrc" \
    VENV_DIRECTORY="${OPT_DIRECTORY:?}/venv" \
    POETRY_HOME="${OPT_DIRECTORY:?}/poetry" \
    PIPX_HOME="${OPT_DIRECTORY:?}/pipx" \
    PIPX_BIN_DIR="${OPT_DIRECTORY:?}/pipx/bin" \
    POETRY_CACHE_DIR="${OPT_DIRECTORY:?}/poetry-cache" \
    PROJECT_DIRECTORY="${OPT_DIRECTORY:?}/repo"

ENV \
    PATH=${POETRY_HOME}/bin:${PIPX_BIN_DIR}:${PATH}:$ORACLE_HOME/bin

# STEP 3: Create a non-root user and directories
# Create a non-root user to avoid running as root
# Create directories for the project, poetry cache, pipx home and virtual environment
RUN \
    useradd "${USER_NAME:?}" --shell /bin/bash --create-home --home-dir "${USER_DIRECTORY:?}" \
    && mkdir -p "${PROJECT_DIRECTORY:?}" "${OPT_DIRECTORY:?}" "${POETRY_CACHE_DIR:?}" "${PIPX_HOME:?}" "${POETRY_HOME:?}" "${VENV_DIRECTORY:?}" "${PIPX_BIN_DIR:?}" \
    && chown -R "${USER_NAME:?}:${USER_NAME:?}" "${PROJECT_DIRECTORY:?}" "${USER_DIRECTORY:?}" "${OPT_DIRECTORY:?}" \
    && chmod -R 755 "${PROJECT_DIRECTORY:?}" "${USER_DIRECTORY:?}" "${OPT_DIRECTORY:?}"

# STEP 4: Install dependencies
# Install system dependencies
# - build-essential - to build Python packages that require compilation
# - nano/vim - text editors (useful to edit files in the container)
# - curl/wget - to fetch files from the internet
# - git - to support pre-commit hooks
# - iputils-ping/telnet - to test network connectivity


RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN \
    python3 -m pip install --upgrade pip==${PIP_VERSION:?} && \
    apt-get update --quiet && \
    apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    nano \
    curl \
    wget \
    vim \
    git \
    tree \
    iputils-ping \
    telnet \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install pipx \
    && pipx ensurepath \
    && pipx install poetry==$POETRY_VERSION